INSERT INTO USERADDRESS(ADDRESS_ID,STREET_NUMBER,ADDRESS_LINE1,ADDRESS_LINE2,LOCALITY,CITY,DISTRICT,PIN_CODE,STATE,COUNTRY) VALUES(1,52,'BS STREET','','KAHO','NA','HAI',5896,'NH','IN');
INSERT INTO USERS (ADDRESS_ID,FIRST_NAME,LAST_NAME,EMAIL_ID,MOBILE_NUMBER,AGE) VALUES (1,'Raja','Jha','rjha301@gmail.com',9635,24);

INSERT INTO USERADDRESS(ADDRESS_ID,STREET_NUMBER,ADDRESS_LINE1,ADDRESS_LINE2,LOCALITY,CITY,DISTRICT,PIN_CODE,STATE,COUNTRY) VALUES(2,72,'LN STREET','','WEX','NA','HAI',58906,'NH','IN');
INSERT INTO USERS (ADDRESS_ID,FIRST_NAME,LAST_NAME,EMAIL_ID,MOBILE_NUMBER,AGE) VALUES (2,'Raj','J','rjha3011@gmail.com',96535,84);